apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent
  namespace: myql
  labels:
    app: dep
spec:
  storageClassName: manual
  capacity:
     storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
      path: /root/volume
