apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
  namespace: myql
  labels:
   app: dep
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 2Gi
